apiVersion: v1
kind: Secret
metadata:
  name: bankflow-secrets
  namespace: bankflow
type: Opaque
stringData:
  POSTGRES_USER: "bankflow"
  POSTGRES_PASSWORD: "bankflow_super_secret_pazzword"
  JWT_SECRET: "BankflowEnterpriseSecretKeyMustBeAtLeast256BitsLongForHMACSHA256SecurityProductionKey"
  GROQ_API_KEY: "gsk_prod_dummy_token_replace_with_live_groq_api_key"
  TWILIO_ACCOUNT_SID: "AC_PROD_TWILIO_ACCOUNT_SID_EXAMPLE"
  TWILIO_AUTH_TOKEN: "prod_twilio_auth_token_example"
