server:
  port: 8083

spring:
  application:
    name: fraud-detection-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fraud-detection-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bankflow.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false

bankflow:
  groq:
    api-key: ${GROQ_API_KEY:}
    model: ${GROQ_MODEL:llama-3.1-70b-versatile}
    endpoint: ${GROQ_ENDPOINT:https://api.groq.com/openai/v1/chat/completions}
  kafka:
    topics:
      txn-events: txn-events
      fraud-alerts: fraud-alerts
      txn-approved: txn-approved
      txn-rejected: txn-rejected

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
